site_name: p2abcengine
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
- Home: index.md
- Documentation:
  - "Installation Guide": "installation-guide.md"
  - "User's Guide": "users-guide.md"
docs_dir: "Documentation/zhaw/"
theme: readthedocs
